### ISSUE TITLE
Test 0pdd

### ISSUE THREAD

**Issue by driver733** [driver733/VKMusicUploader#40]
Test 0pdd by creating a puzzle and then replacing it with a new one.
The new puzzle might not get processed.

**Comment by 0pdd** [comment]
@driver733 the puzzle [#277](https://github.com/driver733/VKUploader/issues/277) is still not solved.

**Comment by 0pdd** [comment]
@driver733 the puzzle [#319](https://github.com/driver733/VK-Uploader/issues/319) is still not solved.
